---
- hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars.yml
  vars:
    app_name: mysite
    app_user: "django_user"
    base_dir: "/home/{{ app_user }}"
    project_dir: "{{ base_dir }}/django-unchained"
    app_dir: "{{ project_dir }}/mysite"
    venv_dir: "{{ project_dir }}/env_3_8_13"
    django_settings: "{{ app_name }}.settings"
    domain: "68.183.35.229"

  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - nginx
          - postgresql
          - postgresql-contrib
          - libpq-dev
        state: present

    - name: Ensure app user exists
      user:
        name: "{{ app_user }}"
        state: present
        shell: /bin/bash
      become: yes

    - name: Ensure base directory exists
      file:
        path: "{{ base_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "0755"
      become: yes

    - name: Ensure project directory exists
      file:
        path: "{{ project_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "0755"
      become: yes

    - name: Create virtual environment
      command: python3.8 -m venv {{ venv_dir }}
      args:
        creates: "{{ venv_dir }}"
      become: yes
      become_user: "{{ app_user }}"

    - name: Install requirements
      pip:
        requirements: /home/django_user/django-unchained/requirements.txt
        virtualenv: /home/django_user/django-unchained/env_3_8_13

    - name: Install django-allauth
      become_user: "{{ app_user }}"
      pip:
        name: django-allauth
        virtualenv: "{{ venv_dir }}"

    - name: Create .env file
      become_user: "{{ app_user }}"
      template:
        src: .env.j2
        dest: "{{ app_dir }}/.env"
        mode: "0600"

    - name: Check if .env file exists
      stat:
        path: "{{ app_dir }}/.env"
      register: env_file
