# Generated by Django 3.2.23 on 2024-10-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_airtabletoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtabletoken',
            name='access_token',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='airtabletoken',
            name='refresh_token',
            field=models.CharField(max_length=5000),
        ),
    ]
